version: "2.4"
services:
  source:
    container_name: csv-datasource
    build: ../stream-source/
    ports:
      - 9999:9999

  mongo:
    image: mongo
    container_name: mongo-container
    volumes:
      - .:/usr/src/code
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root!p4sswd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root!p4sswd
